#!/bin/bash
NC="\033[0m"
LIGHTGREEN="\033[38;5;42m"

# Exit with non-zero status if any of the following commands fail
set -e
# Run shfmt on all files
printf "${LIGHTGREEN}Running shfmt on all files...${NC}\n"
shfmt -d .
